// <auto-generated />
using System;
using LinkedInAutoReply.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LinkedInAutoReply.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260413142924_AddDiscarded")]
    partial class AddDiscarded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("LinkedInAutoReply.Models.RecruiterMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AcceptDraft")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Agency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Approved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssessmentJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeclineDraft")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Discarded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailSubject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FinalDraft")
                        .HasColumnType("TEXT");

                    b.Property<string>("GraphMessageId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HiringCompany")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalMessageText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecruiterName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplyLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplyToAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Verdict")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("RecruiterMessages");
                });

            modelBuilder.Entity("LinkedInAutoReply.Models.SyncState", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("SyncStates");
                });
#pragma warning restore 612, 618
        }
    }
}
